theme: rennes-hugo-theme
_merge: deep
params:
  # RENNES THEME CUSTOM
  custom:
    search_global:
      active: true
      url: "https://chercher.metropole.rennes.fr/?index=ici"
  search:
    active: false