#ECEDI INDEXER CONFIG
content_dirs:
  - /content/fr/pages/nos-dossiers
  - /content/fr/posts
exclude_dirs:
  - /content/fr/posts/2020
has_thematic: false
taxonomies:
  - name : 'Catégories'
    field_name: 'category'
  - name: 'Formats'
    field_name: 'format'