name: ecedi - Content indexation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: choice
        required: true
        options: [ staging, production ]

jobs:
  run-indexer-manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ecedi/rennes-ville-metropole-workflows/.github/workflows/ecedi-search-engine-indexer.yml@staging
    with:
      api_url: ${{ inputs.environment == 'staging' && vars.ECEDI_INDEXER_API_URL_STAGING }}
      app_env: ${{ inputs.environment }}
    secrets:
      ECEDI_INDEXER_API_KEY: ${{ secrets.ECEDI_INDEXER_API_KEY_STAGING }}
      ECEDI_API_BASIC_AUTH: ${{ secrets.ECEDI_API_BASIC_AUTH_STAGING }}

